name: Build Debian Package

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Build package
        run: |
          sudo apt -y update
          sudo apt -y install devscripts equivs unzip
          sudo mk-build-deps --install debian/control --tool "apt -y" --remove
          unzip DtInfoCL_*.zip
          debuild
      - uses: actions/upload-artifact@v7
        with:
          name: deb
          path: ${{ runner.workspace }}/*.deb
